"""tests/test_audio.py — Unit tests for src/audio.py

All tests are offline, require no GPU, no network, and no real audio dataset.
Synthetic fixture WAVs are used (generated by tests/fixtures/make_fixtures.py).

Owner: T-02
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

# Ensure project root is on sys.path for imports
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.audio import (
    AudioFormatError,
    AudioLoadError,
    load_audio,
)

FIXTURES = Path(__file__).parent / "fixtures"
MONO_WAV = FIXTURES / "sample_8words.wav"
STEREO_WAV = FIXTURES / "sample_stereo.wav"
WAV_8KHZ = FIXTURES / "sample_8khz.wav"
EMPTY_WAV = FIXTURES / "sample_empty.wav"

EXPECTED_DURATION_8WORDS_S = 3.20  # see make_fixtures.py
EXPECTED_SR = 16_000


# ---------------------------------------------------------------------------
# Basic load checks
# ---------------------------------------------------------------------------


def test_load_returns_ndarray_and_sr():
    audio, sr = load_audio(MONO_WAV)
    assert isinstance(audio, np.ndarray)
    assert isinstance(sr, int)


def test_load_returns_mono_1d():
    audio, sr = load_audio(MONO_WAV)
    assert audio.ndim == 1, f"Expected 1-D array, got shape {audio.shape}"


def test_load_returns_float32():
    audio, sr = load_audio(MONO_WAV)
    assert audio.dtype == np.float32, f"Expected float32, got {audio.dtype}"


def test_load_sample_rate_is_target():
    _, sr = load_audio(MONO_WAV, sr=16_000)
    assert sr == 16_000

    _, sr2 = load_audio(MONO_WAV, sr=8_000)
    assert sr2 == 8_000


def test_load_correct_duration():
    audio, sr = load_audio(MONO_WAV, sr=EXPECTED_SR)
    duration = len(audio) / sr
    assert abs(duration - EXPECTED_DURATION_8WORDS_S) < 0.05, (
        f"Duration mismatch: got {duration:.3f}s, expected ~{EXPECTED_DURATION_8WORDS_S}s"
    )


def test_load_peak_within_range():
    audio, _ = load_audio(MONO_WAV)
    assert float(np.max(np.abs(audio))) <= 1.0 + 1e-6, "Peak exceeds 1.0 after load"


# ---------------------------------------------------------------------------
# Stereo → mono downmix
# ---------------------------------------------------------------------------


def test_load_stereo_returns_mono():
    audio, sr = load_audio(STEREO_WAV)
    assert audio.ndim == 1, "Stereo file should be downmixed to mono"


def test_load_stereo_same_duration_as_mono():
    mono, _ = load_audio(MONO_WAV)
    stereo, _ = load_audio(STEREO_WAV)
    assert abs(len(mono) - len(stereo)) <= 2, (
        f"Stereo downmix length differs from mono: {len(stereo)} vs {len(mono)}"
    )


# ---------------------------------------------------------------------------
# Resampling
# ---------------------------------------------------------------------------


def test_load_resamples_8khz_to_16khz():
    """File recorded at 8 kHz must be resampled to 16 kHz."""
    audio, sr = load_audio(WAV_8KHZ, sr=16_000)
    assert sr == 16_000
    # Duration should be ~1.0 s → ~16000 samples
    assert abs(len(audio) - 16_000) < 200, (
        f"Resampled length {len(audio)} far from expected 16000"
    )


def test_load_resample_preserves_duration_approx():
    """Resampling should not significantly change perceived duration."""
    audio_16k, _ = load_audio(WAV_8KHZ, sr=16_000)
    audio_8k, _ = load_audio(WAV_8KHZ, sr=8_000)
    dur_16k = len(audio_16k) / 16_000
    dur_8k = len(audio_8k) / 8_000
    assert abs(dur_16k - dur_8k) < 0.05, (
        f"Duration differs after resampling: {dur_16k:.3f}s vs {dur_8k:.3f}s"
    )


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_missing_file_raises_audio_load_error():
    with pytest.raises(AudioLoadError, match="not found"):
        load_audio("/nonexistent/path/audio.wav")


def test_empty_file_raises_audio_load_error():
    with pytest.raises(AudioLoadError):
        load_audio(EMPTY_WAV)


def test_directory_path_raises_audio_load_error():
    with pytest.raises(AudioLoadError):
        load_audio(FIXTURES)  # directory, not a file


def test_invalid_sr_raises_value_error():
    with pytest.raises(ValueError):
        load_audio(MONO_WAV, sr=0)

    with pytest.raises(ValueError):
        load_audio(MONO_WAV, sr=-1)


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------


def test_load_is_deterministic():
    """Same file loaded twice must produce identical arrays."""
    audio1, sr1 = load_audio(MONO_WAV)
    audio2, sr2 = load_audio(MONO_WAV)
    assert sr1 == sr2
    np.testing.assert_array_equal(audio1, audio2)
